"use client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Clock, BookOpen, Target, CheckCircle, Play, Download, Share2, Edit3, Star } from "lucide-react"
import {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

// Dummy course data generated by LLM
const courseData = {
  title: "Organic Chemistry Mastery",
  subject: "Chemistry",
  level: "Intermediate",
  duration: "8 weeks",
  totalChapters: 6,
  estimatedHours: 45,
  description: "A comprehensive course covering fundamental concepts of organic chemistry for JEE preparation",
  chapters: [
    {
      id: 1,
      title: "Introduction to Organic Chemistry",
      description:
        "This foundational chapter introduces you to the fascinating world of organic chemistry. You'll explore the unique properties of carbon that make it the backbone of all organic compounds, understand different types of chemical bonds, and learn the basics of molecular structure. We'll cover hybridization concepts, functional groups, and introduce you to the systematic naming of organic compounds using IUPAC nomenclature.",
      duration: "6 hours",
      difficulty: "Beginner",
      status: "completed",
      progress: 100,
    },
    {
      id: 2,
      title: "Hydrocarbons",
      description:
        "Dive deep into the world of hydrocarbons - the simplest organic compounds containing only carbon and hydrogen. This chapter covers alkanes, alkenes, and alkynes in detail. You'll learn about their structures, physical properties, and chemical reactions. Special emphasis is placed on understanding reaction mechanisms, stereochemistry, and the application of Markovnikov's rule in addition reactions.",
      duration: "8 hours",
      difficulty: "Intermediate",
      status: "in-progress",
      progress: 65,
    },
    {
      id: 3,
      title: "Functional Groups and Their Reactions",
      description:
        "Explore the diverse world of functional groups that give organic compounds their unique properties and reactivity. This comprehensive chapter covers alcohols, phenols, ethers, aldehydes, ketones, carboxylic acids, and their derivatives. You'll master the preparation methods, physical properties, and characteristic reactions of each functional group, with special focus on reaction mechanisms and synthetic applications.",
      duration: "10 hours",
      difficulty: "Intermediate",
      status: "not-started",
      progress: 0,
    },
    {
      id: 4,
      title: "Stereochemistry",
      description:
        "Master the three-dimensional aspects of organic chemistry that are crucial for understanding molecular behavior and reactivity. This advanced chapter covers chirality, optical activity, conformational analysis, and stereochemical outcomes of reactions. You'll learn to identify chiral centers, predict optical rotation, and understand how stereochemistry affects reaction mechanisms and product formation.",
      duration: "7 hours",
      difficulty: "Advanced",
      status: "not-started",
      progress: 0,
    },
    {
      id: 5,
      title: "Reaction Mechanisms",
      description:
        "Develop a deep understanding of how organic reactions occur at the molecular level. This advanced chapter focuses on the fundamental mechanisms that govern organic transformations: substitution, elimination, and addition reactions. You'll learn to predict reaction pathways, understand the factors that influence reaction rates and selectivity, and apply mechanistic principles to solve complex synthetic problems.",
      duration: "9 hours",
      difficulty: "Advanced",
      status: "not-started",
      progress: 0,
    },
    {
      id: 6,
      title: "Biomolecules and Polymers",
      description:
        "Connect organic chemistry to the biological world and modern materials science. This chapter explores the structure and chemistry of important biomolecules including carbohydrates, proteins, and amino acids. You'll also learn about synthetic polymers, their preparation methods, and applications. This chapter bridges the gap between fundamental organic chemistry and its real-world applications in biology and industry.",
      duration: "5 hours",
      difficulty: "Intermediate",
      status: "not-started",
      progress: 0,
    },
  ],
}

export default function ChapterDisplay() {
  const getStatusColor = (status) => {
    switch (status) {
      case "completed":
        return "bg-green-100 text-green-800"
      case "in-progress":
        return "bg-blue-100 text-blue-800"
      case "not-started":
        return "bg-gray-100 text-gray-600"
      default:
        return "bg-gray-100 text-gray-600"
    }
  }

  const getDifficultyColor = (difficulty) => {
    switch (difficulty) {
      case "Beginner":
        return "bg-green-100 text-green-700"
      case "Intermediate":
        return "bg-yellow-100 text-yellow-700"
      case "Advanced":
        return "bg-red-100 text-red-700"
      default:
        return "bg-gray-100 text-gray-600"
    }
  }

  const completedChapters = courseData.chapters.filter((ch) => ch.status === "completed").length
  const overallProgress = (completedChapters / courseData.totalChapters) * 100

  return (
    <div className="min-h-screen bg-gray-50 p-5">
      {/* Header */}
      <div className="px-3">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Vidhur</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/page">Roadmaps</BreadcrumbLink>
           
              <BreadcrumbPage></BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </div>
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="flex items-start justify-between">
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                  <BookOpen className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h1 className="text-3xl font-bold text-gray-900">{courseData.title}</h1>
                  <p className="text-gray-600 mt-1">{courseData.description}</p>
                </div>
              </div>

              <div className="flex items-center gap-6">
                <Badge className={getDifficultyColor(courseData.level)}>{courseData.level}</Badge>
                <div className="flex items-center gap-2 text-gray-600">
                  <Clock className="w-4 h-4" />
                  <span>{courseData.duration}</span>
                </div>
                <div className="flex items-center gap-2 text-gray-600">
                  <Target className="w-4 h-4" />
                  <span>{courseData.estimatedHours} hours</span>
                </div>
                <div className="flex items-center gap-2 text-gray-600">
                  <BookOpen className="w-4 h-4" />
                  <span>{courseData.totalChapters} chapters</span>
                </div>
              </div>

              {/* Progress */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-700">Course Progress</span>
                  <span className="text-sm text-gray-600">
                    {completedChapters}/{courseData.totalChapters} chapters completed
                  </span>
                </div>
                <Progress value={overallProgress} className="h-2" />
              </div>
            </div>

            <div className="flex gap-3">
              <Button variant="outline" className="flex items-center gap-2">
                <Share2 className="w-4 h-4" />
                Share
              </Button>
              <Button variant="outline" className="flex items-center gap-2">
                <Download className="w-4 h-4" />
                Export
              </Button>
              <Button className="bg-black hover:bg-gray-800 text-white flex items-center gap-2">
                <Edit3 className="w-4 h-4" />
                Customize Course
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Course Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="space-y-6">
          {courseData.chapters.map((chapter) => (
            <Card key={chapter.id} className="overflow-hidden">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-4 mb-3">
                      <span className="text-xl font-bold text-gray-900">
                        Chapter {chapter.id}: {chapter.title}
                      </span>
                      <div className="flex items-center gap-2">
                        <Badge className={getStatusColor(chapter.status)}>{chapter.status.replace("-", " ")}</Badge>
                        <Badge className={getDifficultyColor(chapter.difficulty)}>{chapter.difficulty}</Badge>
                      </div>
                    </div>

                    {/* Chapter Description */}
                    <p className="text-gray-600 leading-relaxed">{chapter.description}</p>
                  </div>

                  <div className="flex items-center gap-4 ml-6">
                    <div className="flex items-center gap-2 text-gray-600">
                      <Clock className="w-4 h-4" />
                      <span className="text-sm">{chapter.duration}</span>
                    </div>
                    {chapter.status === "completed" && <CheckCircle className="w-5 h-5 text-green-600" />}
                    {chapter.status === "in-progress" && (
                      <div className="flex items-center gap-2">
                        <div className="w-16 bg-gray-200 rounded-full h-2">
                          <div className="bg-blue-600 h-2 rounded-full" style={{ width: `${chapter.progress}%` }}></div>
                        </div>
                        <span className="text-xs text-gray-600">{chapter.progress}%</span>
                      </div>
                    )}
                  </div>
                </div>
              </CardHeader>

              <CardContent>
                <div className="flex gap-2">
                  {chapter.status === "not-started" && (
                    <Button className="bg-blue-600 hover:bg-blue-700 text-white flex items-center gap-2">
                      <Play className="w-4 h-4" />
                      Start Chapter
                    </Button>
                  )}
                  {chapter.status === "in-progress" && (
                    <Button className="bg-green-600 hover:bg-green-700 text-white flex items-center gap-2">
                      <Play className="w-4 h-4" />
                      Continue
                    </Button>
                  )}
                  {chapter.status === "completed" && (
                    <Button variant="outline" className="flex items-center gap-2">
                      <Star className="w-4 h-4" />
                      Review
                    </Button>
                  )}
                  <Button variant="outline" className="flex items-center gap-2">
                    <Target className="w-4 h-4" />
                    Take Quiz
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  )
}
